name: Hyperparameter Optimization

on:
  push:
    branches: [ main ]
    paths: 
      - 'hyperparameter_optimization.py'
      - 'utils.py'
  pull_request:
    branches: [ main ]
    paths:
      - 'hyperparameter_optimization.py'
      - 'utils.py'
  workflow_dispatch:

jobs:
  optimize-hyperparameters:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install matplotlib scikit-learn numpy
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run hyperparameter optimization
      run: |
        export MPLBACKEND=Agg
        python hyperparameter_optimization.py
    
    - name: Display optimization results
      run: |
        echo "Hyperparameter optimization completed successfully!"
        echo "Check the job logs above for optimal parameters."
